// Code generated by protoc-gen-go. DO NOT EDIT.
// source: krpc.proto

package krpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ConnectionRequest_Type int32

const (
	ConnectionRequest_RPC    ConnectionRequest_Type = 0
	ConnectionRequest_STREAM ConnectionRequest_Type = 1
)

var ConnectionRequest_Type_name = map[int32]string{
	0: "RPC",
	1: "STREAM",
}
var ConnectionRequest_Type_value = map[string]int32{
	"RPC":    0,
	"STREAM": 1,
}

func (x ConnectionRequest_Type) String() string {
	return proto.EnumName(ConnectionRequest_Type_name, int32(x))
}
func (ConnectionRequest_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_krpc_2f9cc8f87eecd690, []int{0, 0}
}

type ConnectionResponse_Status int32

const (
	ConnectionResponse_OK                ConnectionResponse_Status = 0
	ConnectionResponse_MALFORMED_MESSAGE ConnectionResponse_Status = 1
	ConnectionResponse_TIMEOUT           ConnectionResponse_Status = 2
	ConnectionResponse_WRONG_TYPE        ConnectionResponse_Status = 3
)

var ConnectionResponse_Status_name = map[int32]string{
	0: "OK",
	1: "MALFORMED_MESSAGE",
	2: "TIMEOUT",
	3: "WRONG_TYPE",
}
var ConnectionResponse_Status_value = map[string]int32{
	"OK":                0,
	"MALFORMED_MESSAGE": 1,
	"TIMEOUT":           2,
	"WRONG_TYPE":        3,
}

func (x ConnectionResponse_Status) String() string {
	return proto.EnumName(ConnectionResponse_Status_name, int32(x))
}
func (ConnectionResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_krpc_2f9cc8f87eecd690, []int{1, 0}
}

type Type_TypeCode int32

const (
	Type_NONE Type_TypeCode = 0
	// Values
	Type_DOUBLE Type_TypeCode = 1
	Type_FLOAT  Type_TypeCode = 2
	Type_SINT32 Type_TypeCode = 3
	Type_SINT64 Type_TypeCode = 4
	Type_UINT32 Type_TypeCode = 5
	Type_UINT64 Type_TypeCode = 6
	Type_BOOL   Type_TypeCode = 7
	Type_STRING Type_TypeCode = 8
	Type_BYTES  Type_TypeCode = 9
	// Objects
	Type_CLASS       Type_TypeCode = 100
	Type_ENUMERATION Type_TypeCode = 101
	// Messages
	Type_EVENT          Type_TypeCode = 200
	Type_PROCEDURE_CALL Type_TypeCode = 201
	Type_STREAM         Type_TypeCode = 202
	Type_STATUS         Type_TypeCode = 203
	Type_SERVICES       Type_TypeCode = 204
	// Collections
	Type_TUPLE      Type_TypeCode = 300
	Type_LIST       Type_TypeCode = 301
	Type_SET        Type_TypeCode = 302
	Type_DICTIONARY Type_TypeCode = 303
)

var Type_TypeCode_name = map[int32]string{
	0:   "NONE",
	1:   "DOUBLE",
	2:   "FLOAT",
	3:   "SINT32",
	4:   "SINT64",
	5:   "UINT32",
	6:   "UINT64",
	7:   "BOOL",
	8:   "STRING",
	9:   "BYTES",
	100: "CLASS",
	101: "ENUMERATION",
	200: "EVENT",
	201: "PROCEDURE_CALL",
	202: "STREAM",
	203: "STATUS",
	204: "SERVICES",
	300: "TUPLE",
	301: "LIST",
	302: "SET",
	303: "DICTIONARY",
}
var Type_TypeCode_value = map[string]int32{
	"NONE":           0,
	"DOUBLE":         1,
	"FLOAT":          2,
	"SINT32":         3,
	"SINT64":         4,
	"UINT32":         5,
	"UINT64":         6,
	"BOOL":           7,
	"STRING":         8,
	"BYTES":          9,
	"CLASS":          100,
	"ENUMERATION":    101,
	"EVENT":          200,
	"PROCEDURE_CALL": 201,
	"STREAM":         202,
	"STATUS":         203,
	"SERVICES":       204,
	"TUPLE":          300,
	"LIST":           301,
	"SET":            302,
	"DICTIONARY":     303,
}

func (x Type_TypeCode) String() string {
	return proto.EnumName(Type_TypeCode_name, int32(x))
}
func (Type_TypeCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_krpc_2f9cc8f87eecd690, []int{18, 0}
}

type ConnectionRequest struct {
	Type                 ConnectionRequest_Type `protobuf:"varint,1,opt,name=type,proto3,enum=sturdyengine.ConnectionRequest_Type" json:"type,omitempty"`
	ClientName           string                 `protobuf:"bytes,2,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	ClientIdentifier     []byte                 `protobuf:"bytes,3,opt,name=client_identifier,json=clientIdentifier,proto3" json:"client_identifier,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ConnectionRequest) Reset()         { *m = ConnectionRequest{} }
func (m *ConnectionRequest) String() string { return proto.CompactTextString(m) }
func (*ConnectionRequest) ProtoMessage()    {}
func (*ConnectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_krpc_2f9cc8f87eecd690, []int{0}
}
func (m *ConnectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionRequest.Unmarshal(m, b)
}
func (m *ConnectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionRequest.Marshal(b, m, deterministic)
}
func (dst *ConnectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionRequest.Merge(dst, src)
}
func (m *ConnectionRequest) XXX_Size() int {
	return xxx_messageInfo_ConnectionRequest.Size(m)
}
func (m *ConnectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionRequest proto.InternalMessageInfo

func (m *ConnectionRequest) GetType() ConnectionRequest_Type {
	if m != nil {
		return m.Type
	}
	return ConnectionRequest_RPC
}

func (m *ConnectionRequest) GetClientName() string {
	if m != nil {
		return m.ClientName
	}
	return ""
}

func (m *ConnectionRequest) GetClientIdentifier() []byte {
	if m != nil {
		return m.ClientIdentifier
	}
	return nil
}

type ConnectionResponse struct {
	Status               ConnectionResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=sturdyengine.ConnectionResponse_Status" json:"status,omitempty"`
	Message              string                    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ClientIdentifier     []byte                    `protobuf:"bytes,3,opt,name=client_identifier,json=clientIdentifier,proto3" json:"client_identifier,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ConnectionResponse) Reset()         { *m = ConnectionResponse{} }
func (m *ConnectionResponse) String() string { return proto.CompactTextString(m) }
func (*ConnectionResponse) ProtoMessage()    {}
func (*ConnectionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_krpc_2f9cc8f87eecd690, []int{1}
}
func (m *ConnectionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionResponse.Unmarshal(m, b)
}
func (m *ConnectionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionResponse.Marshal(b, m, deterministic)
}
func (dst *ConnectionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionResponse.Merge(dst, src)
}
func (m *ConnectionResponse) XXX_Size() int {
	return xxx_messageInfo_ConnectionResponse.Size(m)
}
func (m *ConnectionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionResponse proto.InternalMessageInfo

func (m *ConnectionResponse) GetStatus() ConnectionResponse_Status {
	if m != nil {
		return m.Status
	}
	return ConnectionResponse_OK
}

func (m *ConnectionResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ConnectionResponse) GetClientIdentifier() []byte {
	if m != nil {
		return m.ClientIdentifier
	}
	return nil
}

type Request struct {
	Calls                []*ProcedureCall `protobuf:"bytes,1,rep,name=calls,proto3" json:"calls,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_krpc_2f9cc8f87eecd690, []int{2}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetCalls() []*ProcedureCall {
	if m != nil {
		return m.Calls
	}
	return nil
}

type ProcedureCall struct {
	Service              string      `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Procedure            string      `protobuf:"bytes,2,opt,name=procedure,proto3" json:"procedure,omitempty"`
	ServiceId            uint32      `protobuf:"varint,4,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	ProcedureId          uint32      `protobuf:"varint,5,opt,name=procedure_id,json=procedureId,proto3" json:"procedure_id,omitempty"`
	Arguments            []*Argument `protobuf:"bytes,3,rep,name=arguments,proto3" json:"arguments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ProcedureCall) Reset()         { *m = ProcedureCall{} }
func (m *ProcedureCall) String() string { return proto.CompactTextString(m) }
func (*ProcedureCall) ProtoMessage()    {}
func (*ProcedureCall) Descriptor() ([]byte, []int) {
	return fileDescriptor_krpc_2f9cc8f87eecd690, []int{3}
}
func (m *ProcedureCall) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcedureCall.Unmarshal(m, b)
}
func (m *ProcedureCall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcedureCall.Marshal(b, m, deterministic)
}
func (dst *ProcedureCall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcedureCall.Merge(dst, src)
}
func (m *ProcedureCall) XXX_Size() int {
	return xxx_messageInfo_ProcedureCall.Size(m)
}
func (m *ProcedureCall) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcedureCall.DiscardUnknown(m)
}

var xxx_messageInfo_ProcedureCall proto.InternalMessageInfo

func (m *ProcedureCall) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *ProcedureCall) GetProcedure() string {
	if m != nil {
		return m.Procedure
	}
	return ""
}

func (m *ProcedureCall) GetServiceId() uint32 {
	if m != nil {
		return m.ServiceId
	}
	return 0
}

func (m *ProcedureCall) GetProcedureId() uint32 {
	if m != nil {
		return m.ProcedureId
	}
	return 0
}

func (m *ProcedureCall) GetArguments() []*Argument {
	if m != nil {
		return m.Arguments
	}
	return nil
}

type Argument struct {
	Position             uint32   `protobuf:"varint,1,opt,name=position,proto3" json:"position,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Argument) Reset()         { *m = Argument{} }
func (m *Argument) String() string { return proto.CompactTextString(m) }
func (*Argument) ProtoMessage()    {}
func (*Argument) Descriptor() ([]byte, []int) {
	return fileDescriptor_krpc_2f9cc8f87eecd690, []int{4}
}
func (m *Argument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Argument.Unmarshal(m, b)
}
func (m *Argument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Argument.Marshal(b, m, deterministic)
}
func (dst *Argument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Argument.Merge(dst, src)
}
func (m *Argument) XXX_Size() int {
	return xxx_messageInfo_Argument.Size(m)
}
func (m *Argument) XXX_DiscardUnknown() {
	xxx_messageInfo_Argument.DiscardUnknown(m)
}

var xxx_messageInfo_Argument proto.InternalMessageInfo

func (m *Argument) GetPosition() uint32 {
	if m != nil {
		return m.Position
	}
	return 0
}

func (m *Argument) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type Response struct {
	Error                *Error             `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Results              []*ProcedureResult `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_krpc_2f9cc8f87eecd690, []int{5}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Response) GetResults() []*ProcedureResult {
	if m != nil {
		return m.Results
	}
	return nil
}

type ProcedureResult struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProcedureResult) Reset()         { *m = ProcedureResult{} }
func (m *ProcedureResult) String() string { return proto.CompactTextString(m) }
func (*ProcedureResult) ProtoMessage()    {}
func (*ProcedureResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_krpc_2f9cc8f87eecd690, []int{6}
}
func (m *ProcedureResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcedureResult.Unmarshal(m, b)
}
func (m *ProcedureResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcedureResult.Marshal(b, m, deterministic)
}
func (dst *ProcedureResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcedureResult.Merge(dst, src)
}
func (m *ProcedureResult) XXX_Size() int {
	return xxx_messageInfo_ProcedureResult.Size(m)
}
func (m *ProcedureResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcedureResult.DiscardUnknown(m)
}

var xxx_messageInfo_ProcedureResult proto.InternalMessageInfo

func (m *ProcedureResult) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *ProcedureResult) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type Error struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	StackTrace           string   `protobuf:"bytes,4,opt,name=stack_trace,json=stackTrace,proto3" json:"stack_trace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_krpc_2f9cc8f87eecd690, []int{7}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (dst *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(dst, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *Error) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Error) GetStackTrace() string {
	if m != nil {
		return m.StackTrace
	}
	return ""
}

type StreamUpdate struct {
	Results              []*StreamResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *StreamUpdate) Reset()         { *m = StreamUpdate{} }
func (m *StreamUpdate) String() string { return proto.CompactTextString(m) }
func (*StreamUpdate) ProtoMessage()    {}
func (*StreamUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_krpc_2f9cc8f87eecd690, []int{8}
}
func (m *StreamUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamUpdate.Unmarshal(m, b)
}
func (m *StreamUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamUpdate.Marshal(b, m, deterministic)
}
func (dst *StreamUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamUpdate.Merge(dst, src)
}
func (m *StreamUpdate) XXX_Size() int {
	return xxx_messageInfo_StreamUpdate.Size(m)
}
func (m *StreamUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_StreamUpdate proto.InternalMessageInfo

func (m *StreamUpdate) GetResults() []*StreamResult {
	if m != nil {
		return m.Results
	}
	return nil
}

type StreamResult struct {
	Id                   uint64           `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Result               *ProcedureResult `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *StreamResult) Reset()         { *m = StreamResult{} }
func (m *StreamResult) String() string { return proto.CompactTextString(m) }
func (*StreamResult) ProtoMessage()    {}
func (*StreamResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_krpc_2f9cc8f87eecd690, []int{9}
}
func (m *StreamResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamResult.Unmarshal(m, b)
}
func (m *StreamResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamResult.Marshal(b, m, deterministic)
}
func (dst *StreamResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamResult.Merge(dst, src)
}
func (m *StreamResult) XXX_Size() int {
	return xxx_messageInfo_StreamResult.Size(m)
}
func (m *StreamResult) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamResult.DiscardUnknown(m)
}

var xxx_messageInfo_StreamResult proto.InternalMessageInfo

func (m *StreamResult) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *StreamResult) GetResult() *ProcedureResult {
	if m != nil {
		return m.Result
	}
	return nil
}

type Services struct {
	Services             []*Service `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Services) Reset()         { *m = Services{} }
func (m *Services) String() string { return proto.CompactTextString(m) }
func (*Services) ProtoMessage()    {}
func (*Services) Descriptor() ([]byte, []int) {
	return fileDescriptor_krpc_2f9cc8f87eecd690, []int{10}
}
func (m *Services) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Services.Unmarshal(m, b)
}
func (m *Services) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Services.Marshal(b, m, deterministic)
}
func (dst *Services) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Services.Merge(dst, src)
}
func (m *Services) XXX_Size() int {
	return xxx_messageInfo_Services.Size(m)
}
func (m *Services) XXX_DiscardUnknown() {
	xxx_messageInfo_Services.DiscardUnknown(m)
}

var xxx_messageInfo_Services proto.InternalMessageInfo

func (m *Services) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

type Service struct {
	Name                 string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Procedures           []*Procedure   `protobuf:"bytes,2,rep,name=procedures,proto3" json:"procedures,omitempty"`
	Classes              []*Class       `protobuf:"bytes,3,rep,name=classes,proto3" json:"classes,omitempty"`
	Enumerations         []*Enumeration `protobuf:"bytes,4,rep,name=enumerations,proto3" json:"enumerations,omitempty"`
	Exceptions           []*Exception   `protobuf:"bytes,5,rep,name=exceptions,proto3" json:"exceptions,omitempty"`
	Documentation        string         `protobuf:"bytes,6,opt,name=documentation,proto3" json:"documentation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_krpc_2f9cc8f87eecd690, []int{11}
}
func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (dst *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(dst, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service) GetProcedures() []*Procedure {
	if m != nil {
		return m.Procedures
	}
	return nil
}

func (m *Service) GetClasses() []*Class {
	if m != nil {
		return m.Classes
	}
	return nil
}

func (m *Service) GetEnumerations() []*Enumeration {
	if m != nil {
		return m.Enumerations
	}
	return nil
}

func (m *Service) GetExceptions() []*Exception {
	if m != nil {
		return m.Exceptions
	}
	return nil
}

func (m *Service) GetDocumentation() string {
	if m != nil {
		return m.Documentation
	}
	return ""
}

type Procedure struct {
	Name                 string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Parameters           []*Parameter `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty"`
	ReturnType           *Type        `protobuf:"bytes,3,opt,name=return_type,json=returnType,proto3" json:"return_type,omitempty"`
	ReturnIsNullable     bool         `protobuf:"varint,4,opt,name=return_is_nullable,json=returnIsNullable,proto3" json:"return_is_nullable,omitempty"`
	Documentation        string       `protobuf:"bytes,5,opt,name=documentation,proto3" json:"documentation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Procedure) Reset()         { *m = Procedure{} }
func (m *Procedure) String() string { return proto.CompactTextString(m) }
func (*Procedure) ProtoMessage()    {}
func (*Procedure) Descriptor() ([]byte, []int) {
	return fileDescriptor_krpc_2f9cc8f87eecd690, []int{12}
}
func (m *Procedure) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Procedure.Unmarshal(m, b)
}
func (m *Procedure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Procedure.Marshal(b, m, deterministic)
}
func (dst *Procedure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Procedure.Merge(dst, src)
}
func (m *Procedure) XXX_Size() int {
	return xxx_messageInfo_Procedure.Size(m)
}
func (m *Procedure) XXX_DiscardUnknown() {
	xxx_messageInfo_Procedure.DiscardUnknown(m)
}

var xxx_messageInfo_Procedure proto.InternalMessageInfo

func (m *Procedure) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Procedure) GetParameters() []*Parameter {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func (m *Procedure) GetReturnType() *Type {
	if m != nil {
		return m.ReturnType
	}
	return nil
}

func (m *Procedure) GetReturnIsNullable() bool {
	if m != nil {
		return m.ReturnIsNullable
	}
	return false
}

func (m *Procedure) GetDocumentation() string {
	if m != nil {
		return m.Documentation
	}
	return ""
}

type Parameter struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 *Type    `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	DefaultValue         []byte   `protobuf:"bytes,3,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Parameter) Reset()         { *m = Parameter{} }
func (m *Parameter) String() string { return proto.CompactTextString(m) }
func (*Parameter) ProtoMessage()    {}
func (*Parameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_krpc_2f9cc8f87eecd690, []int{13}
}
func (m *Parameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Parameter.Unmarshal(m, b)
}
func (m *Parameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Parameter.Marshal(b, m, deterministic)
}
func (dst *Parameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Parameter.Merge(dst, src)
}
func (m *Parameter) XXX_Size() int {
	return xxx_messageInfo_Parameter.Size(m)
}
func (m *Parameter) XXX_DiscardUnknown() {
	xxx_messageInfo_Parameter.DiscardUnknown(m)
}

var xxx_messageInfo_Parameter proto.InternalMessageInfo

func (m *Parameter) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Parameter) GetType() *Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Parameter) GetDefaultValue() []byte {
	if m != nil {
		return m.DefaultValue
	}
	return nil
}

type Class struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Documentation        string   `protobuf:"bytes,2,opt,name=documentation,proto3" json:"documentation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Class) Reset()         { *m = Class{} }
func (m *Class) String() string { return proto.CompactTextString(m) }
func (*Class) ProtoMessage()    {}
func (*Class) Descriptor() ([]byte, []int) {
	return fileDescriptor_krpc_2f9cc8f87eecd690, []int{14}
}
func (m *Class) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Class.Unmarshal(m, b)
}
func (m *Class) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Class.Marshal(b, m, deterministic)
}
func (dst *Class) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Class.Merge(dst, src)
}
func (m *Class) XXX_Size() int {
	return xxx_messageInfo_Class.Size(m)
}
func (m *Class) XXX_DiscardUnknown() {
	xxx_messageInfo_Class.DiscardUnknown(m)
}

var xxx_messageInfo_Class proto.InternalMessageInfo

func (m *Class) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Class) GetDocumentation() string {
	if m != nil {
		return m.Documentation
	}
	return ""
}

type Enumeration struct {
	Name                 string              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Values               []*EnumerationValue `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	Documentation        string              `protobuf:"bytes,3,opt,name=documentation,proto3" json:"documentation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Enumeration) Reset()         { *m = Enumeration{} }
func (m *Enumeration) String() string { return proto.CompactTextString(m) }
func (*Enumeration) ProtoMessage()    {}
func (*Enumeration) Descriptor() ([]byte, []int) {
	return fileDescriptor_krpc_2f9cc8f87eecd690, []int{15}
}
func (m *Enumeration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Enumeration.Unmarshal(m, b)
}
func (m *Enumeration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Enumeration.Marshal(b, m, deterministic)
}
func (dst *Enumeration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Enumeration.Merge(dst, src)
}
func (m *Enumeration) XXX_Size() int {
	return xxx_messageInfo_Enumeration.Size(m)
}
func (m *Enumeration) XXX_DiscardUnknown() {
	xxx_messageInfo_Enumeration.DiscardUnknown(m)
}

var xxx_messageInfo_Enumeration proto.InternalMessageInfo

func (m *Enumeration) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Enumeration) GetValues() []*EnumerationValue {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *Enumeration) GetDocumentation() string {
	if m != nil {
		return m.Documentation
	}
	return ""
}

type EnumerationValue struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                int32    `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	Documentation        string   `protobuf:"bytes,3,opt,name=documentation,proto3" json:"documentation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnumerationValue) Reset()         { *m = EnumerationValue{} }
func (m *EnumerationValue) String() string { return proto.CompactTextString(m) }
func (*EnumerationValue) ProtoMessage()    {}
func (*EnumerationValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_krpc_2f9cc8f87eecd690, []int{16}
}
func (m *EnumerationValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnumerationValue.Unmarshal(m, b)
}
func (m *EnumerationValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnumerationValue.Marshal(b, m, deterministic)
}
func (dst *EnumerationValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnumerationValue.Merge(dst, src)
}
func (m *EnumerationValue) XXX_Size() int {
	return xxx_messageInfo_EnumerationValue.Size(m)
}
func (m *EnumerationValue) XXX_DiscardUnknown() {
	xxx_messageInfo_EnumerationValue.DiscardUnknown(m)
}

var xxx_messageInfo_EnumerationValue proto.InternalMessageInfo

func (m *EnumerationValue) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EnumerationValue) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *EnumerationValue) GetDocumentation() string {
	if m != nil {
		return m.Documentation
	}
	return ""
}

type Exception struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Documentation        string   `protobuf:"bytes,2,opt,name=documentation,proto3" json:"documentation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Exception) Reset()         { *m = Exception{} }
func (m *Exception) String() string { return proto.CompactTextString(m) }
func (*Exception) ProtoMessage()    {}
func (*Exception) Descriptor() ([]byte, []int) {
	return fileDescriptor_krpc_2f9cc8f87eecd690, []int{17}
}
func (m *Exception) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Exception.Unmarshal(m, b)
}
func (m *Exception) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Exception.Marshal(b, m, deterministic)
}
func (dst *Exception) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Exception.Merge(dst, src)
}
func (m *Exception) XXX_Size() int {
	return xxx_messageInfo_Exception.Size(m)
}
func (m *Exception) XXX_DiscardUnknown() {
	xxx_messageInfo_Exception.DiscardUnknown(m)
}

var xxx_messageInfo_Exception proto.InternalMessageInfo

func (m *Exception) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Exception) GetDocumentation() string {
	if m != nil {
		return m.Documentation
	}
	return ""
}

type Type struct {
	Code                 Type_TypeCode `protobuf:"varint,1,opt,name=code,proto3,enum=sturdyengine.Type_TypeCode" json:"code,omitempty"`
	Service              string        `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Name                 string        `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Types                []*Type       `protobuf:"bytes,4,rep,name=types,proto3" json:"types,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Type) Reset()         { *m = Type{} }
func (m *Type) String() string { return proto.CompactTextString(m) }
func (*Type) ProtoMessage()    {}
func (*Type) Descriptor() ([]byte, []int) {
	return fileDescriptor_krpc_2f9cc8f87eecd690, []int{18}
}
func (m *Type) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Type.Unmarshal(m, b)
}
func (m *Type) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Type.Marshal(b, m, deterministic)
}
func (dst *Type) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Type.Merge(dst, src)
}
func (m *Type) XXX_Size() int {
	return xxx_messageInfo_Type.Size(m)
}
func (m *Type) XXX_DiscardUnknown() {
	xxx_messageInfo_Type.DiscardUnknown(m)
}

var xxx_messageInfo_Type proto.InternalMessageInfo

func (m *Type) GetCode() Type_TypeCode {
	if m != nil {
		return m.Code
	}
	return Type_NONE
}

func (m *Type) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *Type) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Type) GetTypes() []*Type {
	if m != nil {
		return m.Types
	}
	return nil
}

type Tuple struct {
	Items                [][]byte `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tuple) Reset()         { *m = Tuple{} }
func (m *Tuple) String() string { return proto.CompactTextString(m) }
func (*Tuple) ProtoMessage()    {}
func (*Tuple) Descriptor() ([]byte, []int) {
	return fileDescriptor_krpc_2f9cc8f87eecd690, []int{19}
}
func (m *Tuple) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tuple.Unmarshal(m, b)
}
func (m *Tuple) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tuple.Marshal(b, m, deterministic)
}
func (dst *Tuple) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tuple.Merge(dst, src)
}
func (m *Tuple) XXX_Size() int {
	return xxx_messageInfo_Tuple.Size(m)
}
func (m *Tuple) XXX_DiscardUnknown() {
	xxx_messageInfo_Tuple.DiscardUnknown(m)
}

var xxx_messageInfo_Tuple proto.InternalMessageInfo

func (m *Tuple) GetItems() [][]byte {
	if m != nil {
		return m.Items
	}
	return nil
}

type List struct {
	Items                [][]byte `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *List) Reset()         { *m = List{} }
func (m *List) String() string { return proto.CompactTextString(m) }
func (*List) ProtoMessage()    {}
func (*List) Descriptor() ([]byte, []int) {
	return fileDescriptor_krpc_2f9cc8f87eecd690, []int{20}
}
func (m *List) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_List.Unmarshal(m, b)
}
func (m *List) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_List.Marshal(b, m, deterministic)
}
func (dst *List) XXX_Merge(src proto.Message) {
	xxx_messageInfo_List.Merge(dst, src)
}
func (m *List) XXX_Size() int {
	return xxx_messageInfo_List.Size(m)
}
func (m *List) XXX_DiscardUnknown() {
	xxx_messageInfo_List.DiscardUnknown(m)
}

var xxx_messageInfo_List proto.InternalMessageInfo

func (m *List) GetItems() [][]byte {
	if m != nil {
		return m.Items
	}
	return nil
}

type Set struct {
	Items                [][]byte `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Set) Reset()         { *m = Set{} }
func (m *Set) String() string { return proto.CompactTextString(m) }
func (*Set) ProtoMessage()    {}
func (*Set) Descriptor() ([]byte, []int) {
	return fileDescriptor_krpc_2f9cc8f87eecd690, []int{21}
}
func (m *Set) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Set.Unmarshal(m, b)
}
func (m *Set) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Set.Marshal(b, m, deterministic)
}
func (dst *Set) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Set.Merge(dst, src)
}
func (m *Set) XXX_Size() int {
	return xxx_messageInfo_Set.Size(m)
}
func (m *Set) XXX_DiscardUnknown() {
	xxx_messageInfo_Set.DiscardUnknown(m)
}

var xxx_messageInfo_Set proto.InternalMessageInfo

func (m *Set) GetItems() [][]byte {
	if m != nil {
		return m.Items
	}
	return nil
}

type Dictionary struct {
	Entries              []*DictionaryEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Dictionary) Reset()         { *m = Dictionary{} }
func (m *Dictionary) String() string { return proto.CompactTextString(m) }
func (*Dictionary) ProtoMessage()    {}
func (*Dictionary) Descriptor() ([]byte, []int) {
	return fileDescriptor_krpc_2f9cc8f87eecd690, []int{22}
}
func (m *Dictionary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dictionary.Unmarshal(m, b)
}
func (m *Dictionary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dictionary.Marshal(b, m, deterministic)
}
func (dst *Dictionary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dictionary.Merge(dst, src)
}
func (m *Dictionary) XXX_Size() int {
	return xxx_messageInfo_Dictionary.Size(m)
}
func (m *Dictionary) XXX_DiscardUnknown() {
	xxx_messageInfo_Dictionary.DiscardUnknown(m)
}

var xxx_messageInfo_Dictionary proto.InternalMessageInfo

func (m *Dictionary) GetEntries() []*DictionaryEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type DictionaryEntry struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DictionaryEntry) Reset()         { *m = DictionaryEntry{} }
func (m *DictionaryEntry) String() string { return proto.CompactTextString(m) }
func (*DictionaryEntry) ProtoMessage()    {}
func (*DictionaryEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_krpc_2f9cc8f87eecd690, []int{23}
}
func (m *DictionaryEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DictionaryEntry.Unmarshal(m, b)
}
func (m *DictionaryEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DictionaryEntry.Marshal(b, m, deterministic)
}
func (dst *DictionaryEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DictionaryEntry.Merge(dst, src)
}
func (m *DictionaryEntry) XXX_Size() int {
	return xxx_messageInfo_DictionaryEntry.Size(m)
}
func (m *DictionaryEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_DictionaryEntry.DiscardUnknown(m)
}

var xxx_messageInfo_DictionaryEntry proto.InternalMessageInfo

func (m *DictionaryEntry) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *DictionaryEntry) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type Stream struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stream) Reset()         { *m = Stream{} }
func (m *Stream) String() string { return proto.CompactTextString(m) }
func (*Stream) ProtoMessage()    {}
func (*Stream) Descriptor() ([]byte, []int) {
	return fileDescriptor_krpc_2f9cc8f87eecd690, []int{24}
}
func (m *Stream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stream.Unmarshal(m, b)
}
func (m *Stream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stream.Marshal(b, m, deterministic)
}
func (dst *Stream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stream.Merge(dst, src)
}
func (m *Stream) XXX_Size() int {
	return xxx_messageInfo_Stream.Size(m)
}
func (m *Stream) XXX_DiscardUnknown() {
	xxx_messageInfo_Stream.DiscardUnknown(m)
}

var xxx_messageInfo_Stream proto.InternalMessageInfo

func (m *Stream) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Event struct {
	Stream               *Stream  `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_krpc_2f9cc8f87eecd690, []int{25}
}
func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (dst *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(dst, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetStream() *Stream {
	if m != nil {
		return m.Stream
	}
	return nil
}

type Status struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	BytesRead            uint64   `protobuf:"varint,2,opt,name=bytes_read,json=bytesRead,proto3" json:"bytes_read,omitempty"`
	BytesWritten         uint64   `protobuf:"varint,3,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	BytesReadRate        float32  `protobuf:"fixed32,4,opt,name=bytes_read_rate,json=bytesReadRate,proto3" json:"bytes_read_rate,omitempty"`
	BytesWrittenRate     float32  `protobuf:"fixed32,5,opt,name=bytes_written_rate,json=bytesWrittenRate,proto3" json:"bytes_written_rate,omitempty"`
	RpcsExecuted         uint64   `protobuf:"varint,6,opt,name=rpcs_executed,json=rpcsExecuted,proto3" json:"rpcs_executed,omitempty"`
	RpcRate              float32  `protobuf:"fixed32,7,opt,name=rpc_rate,json=rpcRate,proto3" json:"rpc_rate,omitempty"`
	OneRpcPerUpdate      bool     `protobuf:"varint,8,opt,name=one_rpc_per_update,json=oneRpcPerUpdate,proto3" json:"one_rpc_per_update,omitempty"`
	MaxTimePerUpdate     uint32   `protobuf:"varint,9,opt,name=max_time_per_update,json=maxTimePerUpdate,proto3" json:"max_time_per_update,omitempty"`
	AdaptiveRateControl  bool     `protobuf:"varint,10,opt,name=adaptive_rate_control,json=adaptiveRateControl,proto3" json:"adaptive_rate_control,omitempty"`
	BlockingRecv         bool     `protobuf:"varint,11,opt,name=blocking_recv,json=blockingRecv,proto3" json:"blocking_recv,omitempty"`
	RecvTimeout          uint32   `protobuf:"varint,12,opt,name=recv_timeout,json=recvTimeout,proto3" json:"recv_timeout,omitempty"`
	TimePerRpcUpdate     float32  `protobuf:"fixed32,13,opt,name=time_per_rpc_update,json=timePerRpcUpdate,proto3" json:"time_per_rpc_update,omitempty"`
	PollTimePerRpcUpdate float32  `protobuf:"fixed32,14,opt,name=poll_time_per_rpc_update,json=pollTimePerRpcUpdate,proto3" json:"poll_time_per_rpc_update,omitempty"`
	ExecTimePerRpcUpdate float32  `protobuf:"fixed32,15,opt,name=exec_time_per_rpc_update,json=execTimePerRpcUpdate,proto3" json:"exec_time_per_rpc_update,omitempty"`
	StreamRpcs           uint32   `protobuf:"varint,16,opt,name=stream_rpcs,json=streamRpcs,proto3" json:"stream_rpcs,omitempty"`
	StreamRpcsExecuted   uint64   `protobuf:"varint,17,opt,name=stream_rpcs_executed,json=streamRpcsExecuted,proto3" json:"stream_rpcs_executed,omitempty"`
	StreamRpcRate        float32  `protobuf:"fixed32,18,opt,name=stream_rpc_rate,json=streamRpcRate,proto3" json:"stream_rpc_rate,omitempty"`
	TimePerStreamUpdate  float32  `protobuf:"fixed32,19,opt,name=time_per_stream_update,json=timePerStreamUpdate,proto3" json:"time_per_stream_update,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_krpc_2f9cc8f87eecd690, []int{26}
}
func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (dst *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(dst, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Status) GetBytesRead() uint64 {
	if m != nil {
		return m.BytesRead
	}
	return 0
}

func (m *Status) GetBytesWritten() uint64 {
	if m != nil {
		return m.BytesWritten
	}
	return 0
}

func (m *Status) GetBytesReadRate() float32 {
	if m != nil {
		return m.BytesReadRate
	}
	return 0
}

func (m *Status) GetBytesWrittenRate() float32 {
	if m != nil {
		return m.BytesWrittenRate
	}
	return 0
}

func (m *Status) GetRpcsExecuted() uint64 {
	if m != nil {
		return m.RpcsExecuted
	}
	return 0
}

func (m *Status) GetRpcRate() float32 {
	if m != nil {
		return m.RpcRate
	}
	return 0
}

func (m *Status) GetOneRpcPerUpdate() bool {
	if m != nil {
		return m.OneRpcPerUpdate
	}
	return false
}

func (m *Status) GetMaxTimePerUpdate() uint32 {
	if m != nil {
		return m.MaxTimePerUpdate
	}
	return 0
}

func (m *Status) GetAdaptiveRateControl() bool {
	if m != nil {
		return m.AdaptiveRateControl
	}
	return false
}

func (m *Status) GetBlockingRecv() bool {
	if m != nil {
		return m.BlockingRecv
	}
	return false
}

func (m *Status) GetRecvTimeout() uint32 {
	if m != nil {
		return m.RecvTimeout
	}
	return 0
}

func (m *Status) GetTimePerRpcUpdate() float32 {
	if m != nil {
		return m.TimePerRpcUpdate
	}
	return 0
}

func (m *Status) GetPollTimePerRpcUpdate() float32 {
	if m != nil {
		return m.PollTimePerRpcUpdate
	}
	return 0
}

func (m *Status) GetExecTimePerRpcUpdate() float32 {
	if m != nil {
		return m.ExecTimePerRpcUpdate
	}
	return 0
}

func (m *Status) GetStreamRpcs() uint32 {
	if m != nil {
		return m.StreamRpcs
	}
	return 0
}

func (m *Status) GetStreamRpcsExecuted() uint64 {
	if m != nil {
		return m.StreamRpcsExecuted
	}
	return 0
}

func (m *Status) GetStreamRpcRate() float32 {
	if m != nil {
		return m.StreamRpcRate
	}
	return 0
}

func (m *Status) GetTimePerStreamUpdate() float32 {
	if m != nil {
		return m.TimePerStreamUpdate
	}
	return 0
}

type MultiplexedRequest struct {
	ConnectionRequest    *ConnectionRequest `protobuf:"bytes,1,opt,name=connection_request,json=connectionRequest,proto3" json:"connection_request,omitempty"`
	Request              *Request           `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *MultiplexedRequest) Reset()         { *m = MultiplexedRequest{} }
func (m *MultiplexedRequest) String() string { return proto.CompactTextString(m) }
func (*MultiplexedRequest) ProtoMessage()    {}
func (*MultiplexedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_krpc_2f9cc8f87eecd690, []int{27}
}
func (m *MultiplexedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiplexedRequest.Unmarshal(m, b)
}
func (m *MultiplexedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiplexedRequest.Marshal(b, m, deterministic)
}
func (dst *MultiplexedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiplexedRequest.Merge(dst, src)
}
func (m *MultiplexedRequest) XXX_Size() int {
	return xxx_messageInfo_MultiplexedRequest.Size(m)
}
func (m *MultiplexedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiplexedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MultiplexedRequest proto.InternalMessageInfo

func (m *MultiplexedRequest) GetConnectionRequest() *ConnectionRequest {
	if m != nil {
		return m.ConnectionRequest
	}
	return nil
}

func (m *MultiplexedRequest) GetRequest() *Request {
	if m != nil {
		return m.Request
	}
	return nil
}

type MultiplexedResponse struct {
	Response             *Response     `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	StreamUpdate         *StreamUpdate `protobuf:"bytes,2,opt,name=stream_update,json=streamUpdate,proto3" json:"stream_update,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *MultiplexedResponse) Reset()         { *m = MultiplexedResponse{} }
func (m *MultiplexedResponse) String() string { return proto.CompactTextString(m) }
func (*MultiplexedResponse) ProtoMessage()    {}
func (*MultiplexedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_krpc_2f9cc8f87eecd690, []int{28}
}
func (m *MultiplexedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiplexedResponse.Unmarshal(m, b)
}
func (m *MultiplexedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiplexedResponse.Marshal(b, m, deterministic)
}
func (dst *MultiplexedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiplexedResponse.Merge(dst, src)
}
func (m *MultiplexedResponse) XXX_Size() int {
	return xxx_messageInfo_MultiplexedResponse.Size(m)
}
func (m *MultiplexedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiplexedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MultiplexedResponse proto.InternalMessageInfo

func (m *MultiplexedResponse) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *MultiplexedResponse) GetStreamUpdate() *StreamUpdate {
	if m != nil {
		return m.StreamUpdate
	}
	return nil
}

func init() {
	proto.RegisterType((*ConnectionRequest)(nil), "sturdyengine.ConnectionRequest")
	proto.RegisterType((*ConnectionResponse)(nil), "sturdyengine.ConnectionResponse")
	proto.RegisterType((*Request)(nil), "sturdyengine.Request")
	proto.RegisterType((*ProcedureCall)(nil), "sturdyengine.ProcedureCall")
	proto.RegisterType((*Argument)(nil), "sturdyengine.Argument")
	proto.RegisterType((*Response)(nil), "sturdyengine.Response")
	proto.RegisterType((*ProcedureResult)(nil), "sturdyengine.ProcedureResult")
	proto.RegisterType((*Error)(nil), "sturdyengine.Error")
	proto.RegisterType((*StreamUpdate)(nil), "sturdyengine.StreamUpdate")
	proto.RegisterType((*StreamResult)(nil), "sturdyengine.StreamResult")
	proto.RegisterType((*Services)(nil), "sturdyengine.Services")
	proto.RegisterType((*Service)(nil), "sturdyengine.Service")
	proto.RegisterType((*Procedure)(nil), "sturdyengine.Procedure")
	proto.RegisterType((*Parameter)(nil), "sturdyengine.Parameter")
	proto.RegisterType((*Class)(nil), "sturdyengine.Class")
	proto.RegisterType((*Enumeration)(nil), "sturdyengine.Enumeration")
	proto.RegisterType((*EnumerationValue)(nil), "sturdyengine.EnumerationValue")
	proto.RegisterType((*Exception)(nil), "sturdyengine.Exception")
	proto.RegisterType((*Type)(nil), "sturdyengine.Type")
	proto.RegisterType((*Tuple)(nil), "sturdyengine.Tuple")
	proto.RegisterType((*List)(nil), "sturdyengine.List")
	proto.RegisterType((*Set)(nil), "sturdyengine.Set")
	proto.RegisterType((*Dictionary)(nil), "sturdyengine.Dictionary")
	proto.RegisterType((*DictionaryEntry)(nil), "sturdyengine.DictionaryEntry")
	proto.RegisterType((*Stream)(nil), "sturdyengine.Stream")
	proto.RegisterType((*Event)(nil), "sturdyengine.Event")
	proto.RegisterType((*Status)(nil), "sturdyengine.Status")
	proto.RegisterType((*MultiplexedRequest)(nil), "sturdyengine.MultiplexedRequest")
	proto.RegisterType((*MultiplexedResponse)(nil), "sturdyengine.MultiplexedResponse")
	proto.RegisterEnum("sturdyengine.ConnectionRequest_Type", ConnectionRequest_Type_name, ConnectionRequest_Type_value)
	proto.RegisterEnum("sturdyengine.ConnectionResponse_Status", ConnectionResponse_Status_name, ConnectionResponse_Status_value)
	proto.RegisterEnum("sturdyengine.Type_TypeCode", Type_TypeCode_name, Type_TypeCode_value)
}

func init() { proto.RegisterFile("krpc.proto", fileDescriptor_krpc_2f9cc8f87eecd690) }

var fileDescriptor_krpc_2f9cc8f87eecd690 = []byte{
	// 1671 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x58, 0x4b, 0x6f, 0xe3, 0xd6,
	0x15, 0x0e, 0xf5, 0xd6, 0x91, 0x64, 0xd3, 0xd7, 0x33, 0x53, 0x26, 0x93, 0x69, 0x5c, 0x26, 0x98,
	0xba, 0xc8, 0xc4, 0x69, 0x3c, 0x93, 0x49, 0x0b, 0x24, 0x08, 0x34, 0x32, 0x33, 0x10, 0x2a, 0x4b,
	0xc6, 0x25, 0x35, 0xc1, 0xac, 0x08, 0x0e, 0x79, 0x33, 0x20, 0x4c, 0x91, 0xec, 0xe5, 0xa5, 0x6b,
	0xaf, 0xba, 0xef, 0xba, 0xfd, 0x05, 0x01, 0xba, 0xea, 0x63, 0xdb, 0x5d, 0xb7, 0x7d, 0xfd, 0x89,
	0xf6, 0x97, 0x14, 0xf7, 0x41, 0x8a, 0x92, 0xa9, 0xa6, 0x83, 0x6c, 0x0c, 0xde, 0x73, 0xbe, 0x73,
	0xf8, 0x9d, 0xc7, 0xe5, 0x39, 0x32, 0xc0, 0x25, 0x4d, 0xfd, 0x93, 0x94, 0x26, 0x2c, 0x41, 0xc3,
	0x8c, 0xe5, 0x34, 0xb8, 0x21, 0xf1, 0xeb, 0x30, 0x26, 0xe6, 0x5f, 0x34, 0x38, 0x98, 0x24, 0x71,
	0x4c, 0x7c, 0x16, 0x26, 0x31, 0x26, 0xbf, 0xcc, 0x49, 0xc6, 0xd0, 0xcf, 0xa0, 0xc5, 0x6e, 0x52,
	0x62, 0x68, 0x47, 0xda, 0xf1, 0xde, 0xe9, 0x07, 0x27, 0x55, 0x93, 0x93, 0x5b, 0xf0, 0x13, 0xe7,
	0x26, 0x25, 0x58, 0x58, 0xa0, 0xf7, 0x60, 0xe0, 0x47, 0x21, 0x89, 0x99, 0x1b, 0x7b, 0x2b, 0x62,
	0x34, 0x8e, 0xb4, 0xe3, 0x3e, 0x06, 0x29, 0x9a, 0x7b, 0x2b, 0x82, 0x3e, 0x84, 0x03, 0x05, 0x08,
	0x03, 0x12, 0xb3, 0xf0, 0x9b, 0x90, 0x50, 0xa3, 0x79, 0xa4, 0x1d, 0x0f, 0xb1, 0x2e, 0x15, 0xd3,
	0x52, 0x6e, 0xde, 0x87, 0x16, 0xf7, 0x8d, 0xba, 0xd0, 0xc4, 0x17, 0x13, 0xfd, 0x2d, 0x04, 0xd0,
	0xb1, 0x1d, 0x6c, 0x8d, 0xcf, 0x75, 0xcd, 0xfc, 0x8f, 0x06, 0xa8, 0xca, 0x25, 0x4b, 0x93, 0x38,
	0x23, 0xe8, 0x4b, 0xe8, 0x64, 0xcc, 0x63, 0x79, 0xa6, 0xd8, 0xff, 0x78, 0x37, 0x7b, 0x69, 0x71,
	0x62, 0x0b, 0x38, 0x56, 0x66, 0xc8, 0x80, 0xee, 0x8a, 0x64, 0x99, 0xf7, 0xba, 0xa0, 0x5f, 0x1c,
	0xdf, 0x8c, 0xfb, 0x19, 0x74, 0xa4, 0x63, 0xd4, 0x81, 0xc6, 0xe2, 0x17, 0xfa, 0x5b, 0xe8, 0x2e,
	0x1c, 0x9c, 0x8f, 0x67, 0x5f, 0x2d, 0xf0, 0xb9, 0x75, 0xe6, 0x9e, 0x5b, 0xb6, 0x3d, 0x7e, 0x6e,
	0xe9, 0x1a, 0x1a, 0x40, 0xd7, 0x99, 0x9e, 0x5b, 0x8b, 0xa5, 0xa3, 0x37, 0xd0, 0x1e, 0xc0, 0xd7,
	0x78, 0x31, 0x7f, 0xee, 0x3a, 0x2f, 0x2f, 0x2c, 0xbd, 0x69, 0x7e, 0x0e, 0xdd, 0xa2, 0x28, 0x9f,
	0x40, 0xdb, 0xf7, 0xa2, 0x88, 0xc7, 0xd5, 0x3c, 0x1e, 0x9c, 0xde, 0xdf, 0x8c, 0xeb, 0x82, 0x26,
	0x3e, 0x09, 0x72, 0x4a, 0x26, 0x5e, 0x14, 0x61, 0x89, 0x34, 0xff, 0xaa, 0xc1, 0x68, 0x43, 0xc1,
	0x83, 0xcb, 0x08, 0xbd, 0x0a, 0x7d, 0x59, 0xdc, 0x3e, 0x2e, 0x8e, 0xe8, 0x5d, 0xe8, 0xa7, 0x05,
	0x54, 0x05, 0xbe, 0x16, 0xa0, 0x07, 0x00, 0x0a, 0xe8, 0x86, 0x81, 0xd1, 0x3a, 0xd2, 0x8e, 0x47,
	0xb8, 0xaf, 0x24, 0xd3, 0x00, 0xfd, 0x08, 0x86, 0x25, 0x96, 0x03, 0xda, 0x02, 0x30, 0x28, 0x65,
	0xd3, 0x00, 0x3d, 0x81, 0xbe, 0x47, 0x5f, 0xe7, 0x2b, 0x12, 0xb3, 0xcc, 0x68, 0x8a, 0x10, 0xee,
	0x6d, 0x86, 0x30, 0x56, 0x6a, 0xbc, 0x06, 0x9a, 0x9f, 0x43, 0xaf, 0x10, 0xa3, 0x77, 0xa0, 0x97,
	0x26, 0x59, 0xc8, 0x6b, 0x27, 0xc8, 0x8f, 0x70, 0x79, 0x46, 0x77, 0xa0, 0x7d, 0xe5, 0x45, 0xb9,
	0x64, 0x3e, 0xc4, 0xf2, 0x60, 0xc6, 0xd0, 0x2b, 0xfb, 0xe2, 0x27, 0xd0, 0x26, 0x94, 0x26, 0x54,
	0x98, 0x0e, 0x4e, 0x0f, 0x37, 0xdf, 0x6d, 0x71, 0x15, 0x96, 0x08, 0xf4, 0x19, 0x74, 0x29, 0xc9,
	0xf2, 0x88, 0x65, 0x46, 0x43, 0x10, 0x7d, 0xb0, 0x23, 0xd7, 0x58, 0xa0, 0x70, 0x81, 0x36, 0x31,
	0xec, 0x6f, 0xe9, 0xde, 0xe4, 0xb5, 0xf5, 0x31, 0x5c, 0x43, 0x5b, 0xa0, 0xfe, 0x47, 0xe9, 0x10,
	0xb4, 0x2a, 0xb7, 0x4d, 0x3c, 0xa3, 0x23, 0x18, 0x04, 0x24, 0xf3, 0x69, 0x98, 0x8a, 0x7c, 0x35,
	0x85, 0xaa, 0x2a, 0xe2, 0x57, 0x35, 0x63, 0x9e, 0x7f, 0xe9, 0x32, 0xea, 0xf9, 0x44, 0xd4, 0xb4,
	0x8f, 0x41, 0x88, 0x1c, 0x2e, 0x31, 0xcf, 0x60, 0x68, 0x33, 0x4a, 0xbc, 0xd5, 0x32, 0x0d, 0x3c,
	0x46, 0xd0, 0x93, 0x75, 0x5a, 0x64, 0x0b, 0xbe, 0xb3, 0x19, 0x8c, 0x04, 0x6f, 0xe7, 0x64, 0x59,
	0x78, 0x51, 0x09, 0xd9, 0x83, 0x46, 0x18, 0x88, 0x08, 0x5a, 0xb8, 0x11, 0x06, 0xe8, 0x53, 0xe8,
	0x48, 0xa8, 0xa0, 0xff, 0x9d, 0xb9, 0x56, 0x60, 0xf3, 0x0b, 0xe8, 0xd9, 0x32, 0xfc, 0x0c, 0x7d,
	0x02, 0x3d, 0x95, 0x8a, 0x82, 0xd9, 0xdd, 0x2d, 0x66, 0x52, 0x8b, 0x4b, 0x98, 0xf9, 0x6d, 0x03,
	0xba, 0xf6, 0x56, 0xfa, 0xb4, 0x4a, 0xfa, 0x3e, 0x03, 0x28, 0x9b, 0xb7, 0xe8, 0x82, 0x1f, 0xec,
	0x62, 0x56, 0x81, 0xa2, 0x8f, 0xa0, 0xeb, 0x47, 0x5e, 0x96, 0x91, 0xa2, 0xc9, 0xb7, 0x2a, 0x3e,
	0xe1, 0x4a, 0x5c, 0x60, 0xd0, 0x17, 0x30, 0x24, 0x71, 0xbe, 0x22, 0xd4, 0xe3, 0x35, 0xc9, 0x8c,
	0x96, 0xb0, 0x79, 0x7b, 0xab, 0x4b, 0xd6, 0x08, 0xbc, 0x01, 0xe7, 0x34, 0xc9, 0xb5, 0x4f, 0x52,
	0x69, 0xdc, 0xae, 0xa3, 0x69, 0x15, 0x7a, 0x5c, 0x81, 0xa2, 0x0f, 0x60, 0x14, 0x24, 0xbe, 0xb8,
	0x57, 0xc2, 0x95, 0xd1, 0x11, 0xc1, 0x6f, 0x0a, 0xcd, 0x7f, 0x6b, 0xd0, 0x2f, 0xc3, 0xdc, 0x99,
	0x27, 0x8f, 0x7a, 0x2b, 0xc2, 0x08, 0xdd, 0x95, 0xa7, 0x42, 0x8f, 0x2b, 0x50, 0xf4, 0x18, 0x06,
	0x94, 0xb0, 0x9c, 0xc6, 0xae, 0x98, 0x34, 0x4d, 0x51, 0x7b, 0xb4, 0x69, 0x29, 0xe6, 0x0a, 0x48,
	0x98, 0x98, 0x03, 0x8f, 0x00, 0x29, 0xa3, 0x30, 0x73, 0xe3, 0x3c, 0x8a, 0xbc, 0x57, 0x91, 0xec,
	0xdc, 0x1e, 0xd6, 0xa5, 0x66, 0x9a, 0xcd, 0x95, 0xfc, 0x76, 0x8c, 0xed, 0xba, 0x18, 0x23, 0xe8,
	0x97, 0x0c, 0x6b, 0x43, 0x7c, 0xa8, 0x86, 0x61, 0x63, 0x27, 0x45, 0x39, 0xfa, 0xde, 0x87, 0x51,
	0x40, 0xbe, 0xf1, 0xf2, 0x88, 0xb9, 0xf2, 0x1a, 0xcb, 0xc9, 0x30, 0x54, 0xc2, 0x17, 0xe2, 0x36,
	0x8f, 0xa1, 0x2d, 0x3a, 0xa0, 0xf6, 0x4d, 0xb7, 0x08, 0x37, 0xea, 0x08, 0xff, 0x1a, 0x06, 0x95,
	0x86, 0xa8, 0x75, 0xf4, 0x14, 0x3a, 0x82, 0x42, 0x51, 0x91, 0x1f, 0xee, 0xec, 0x27, 0xc1, 0x0a,
	0x2b, 0xf4, 0x6d, 0x02, 0xcd, 0x3a, 0x02, 0xaf, 0x40, 0xdf, 0xf6, 0x50, 0xcb, 0x62, 0xe3, 0x7b,
	0xd6, 0x56, 0xdf, 0xb3, 0xff, 0xf3, 0x1d, 0x16, 0xf4, 0xcb, 0xc6, 0xfd, 0x1e, 0xb9, 0xfa, 0x7d,
	0x53, 0x6d, 0x10, 0x1f, 0x43, 0xcb, 0x4f, 0x82, 0x62, 0xa3, 0xb9, 0x7f, 0xbb, 0x88, 0xe2, 0xcf,
	0x24, 0x09, 0x08, 0x16, 0xc0, 0xea, 0xd7, 0xb6, 0x51, 0xff, 0xb5, 0x6d, 0x56, 0xd8, 0x1c, 0x43,
	0x9b, 0xf7, 0x40, 0x71, 0x7f, 0xeb, 0x9a, 0x44, 0x02, 0xcc, 0xdf, 0x36, 0xa0, 0x57, 0xbc, 0x0a,
	0xf5, 0xa0, 0x35, 0x5f, 0xcc, 0x2d, 0xb9, 0xd8, 0x9c, 0x2d, 0x96, 0xcf, 0x66, 0x7c, 0x21, 0xe8,
	0x43, 0xfb, 0xab, 0xd9, 0x62, 0xcc, 0xd7, 0x01, 0xbe, 0xef, 0x4c, 0xe7, 0xce, 0xe3, 0x53, 0xbd,
	0x59, 0x3c, 0x3f, 0x7d, 0xa2, 0xb7, 0xf8, 0xf3, 0x52, 0xca, 0xdb, 0xc5, 0xf3, 0xd3, 0x27, 0x7a,
	0x87, 0x3b, 0x7c, 0xb6, 0x58, 0xcc, 0xf4, 0xae, 0xda, 0x94, 0xa6, 0xf3, 0xe7, 0x7a, 0x8f, 0x3b,
	0x7c, 0xf6, 0xd2, 0xb1, 0x6c, 0xbd, 0xcf, 0x1f, 0x27, 0xb3, 0xb1, 0x6d, 0xeb, 0x01, 0xda, 0x87,
	0x81, 0x35, 0x5f, 0x9e, 0x5b, 0x78, 0xec, 0x4c, 0x17, 0x73, 0x9d, 0x20, 0x80, 0xb6, 0xf5, 0xc2,
	0x9a, 0x3b, 0xfa, 0xdf, 0x34, 0x74, 0x08, 0x7b, 0x17, 0x78, 0x31, 0xb1, 0xce, 0x96, 0xd8, 0x72,
	0x27, 0xe3, 0xd9, 0x4c, 0xff, 0x3b, 0xdf, 0x54, 0x8a, 0xed, 0xeb, 0x1f, 0xea, 0x30, 0x76, 0x96,
	0xb6, 0xfe, 0x4f, 0x0d, 0x8d, 0xa0, 0x67, 0x5b, 0xf8, 0xc5, 0x74, 0x62, 0xd9, 0xfa, 0xbf, 0x34,
	0xee, 0xc9, 0x59, 0x5e, 0xcc, 0x2c, 0xfd, 0x0f, 0x0d, 0xd4, 0x87, 0xd6, 0x6c, 0x6a, 0x3b, 0xfa,
	0x1f, 0x1b, 0xa8, 0x07, 0x4d, 0xdb, 0x72, 0xf4, 0x3f, 0x35, 0xd0, 0x3e, 0xc0, 0xd9, 0x74, 0xc2,
	0xdf, 0x3b, 0xc6, 0x2f, 0xf5, 0x3f, 0x37, 0xcc, 0x07, 0xd0, 0x76, 0xf2, 0x34, 0x12, 0x4d, 0x13,
	0x32, 0xb2, 0x92, 0x1f, 0xf2, 0x21, 0x96, 0x07, 0xf3, 0x5d, 0x68, 0xcd, 0xc2, 0x8c, 0xed, 0xd0,
	0xde, 0x87, 0xa6, 0x4d, 0x76, 0x29, 0x2d, 0x80, 0xb3, 0x50, 0x2c, 0x7c, 0x1e, 0xbd, 0xe1, 0xa3,
	0x9d, 0xc4, 0x8c, 0x86, 0xe5, 0xa4, 0xd8, 0x1a, 0x37, 0x6b, 0xa8, 0x15, 0x33, 0x7a, 0x83, 0x0b,
	0xb4, 0xf9, 0x73, 0xd8, 0xdf, 0xd2, 0x21, 0x1d, 0x9a, 0x97, 0xe4, 0x46, 0xb4, 0xd4, 0x10, 0xf3,
	0xc7, 0x1d, 0x13, 0xdc, 0xe0, 0x9b, 0x20, 0x9f, 0x80, 0xdb, 0xb3, 0xcf, 0xfc, 0x14, 0xda, 0xd6,
	0x15, 0x5f, 0x6d, 0x1e, 0xf1, 0xa5, 0x95, 0x43, 0xd4, 0x9a, 0x70, 0xa7, 0x76, 0xb2, 0x2a, 0x8c,
	0xf9, 0x6d, 0xa7, 0xdc, 0x2d, 0x0d, 0xe8, 0x5e, 0x11, 0x9a, 0x15, 0x2b, 0x51, 0x1f, 0x17, 0x47,
	0xbe, 0xb1, 0xbd, 0xba, 0x61, 0x24, 0x73, 0x29, 0xf1, 0x02, 0x41, 0xa8, 0x85, 0xfb, 0x42, 0x82,
	0x89, 0x17, 0xf0, 0xaf, 0x95, 0x54, 0xff, 0x8a, 0x86, 0x8c, 0x11, 0x79, 0x0d, 0x5b, 0x78, 0x28,
	0x84, 0x5f, 0x4b, 0x19, 0x7a, 0x08, 0xfb, 0x6b, 0x1f, 0x2e, 0xf5, 0x98, 0xfc, 0xd8, 0x36, 0xf0,
	0xa8, 0x74, 0x84, 0xf9, 0x66, 0xf0, 0x08, 0xd0, 0x86, 0x33, 0x09, 0x6d, 0x0b, 0xa8, 0x5e, 0xf5,
	0x28, 0xd0, 0xef, 0xc3, 0x88, 0xa6, 0x7e, 0xe6, 0x92, 0x6b, 0xe2, 0xe7, 0x8c, 0x04, 0x62, 0xf6,
	0xb4, 0xf0, 0x90, 0x0b, 0x2d, 0x25, 0x43, 0x6f, 0x43, 0x8f, 0xa6, 0xbe, 0x74, 0xd4, 0x15, 0x8e,
	0xba, 0x34, 0xf5, 0x85, 0xfd, 0x87, 0x80, 0x92, 0x98, 0xb8, 0x5c, 0x9d, 0x12, 0xea, 0xe6, 0x62,
	0x3b, 0x31, 0x7a, 0x62, 0x0a, 0xec, 0x27, 0x31, 0xc1, 0xa9, 0x7f, 0x41, 0xa8, 0x5a, 0x5a, 0x3e,
	0x82, 0xc3, 0x95, 0x77, 0xed, 0xb2, 0x70, 0x45, 0xaa, 0xe8, 0xbe, 0xd8, 0x1f, 0xf5, 0x95, 0x77,
	0xed, 0x84, 0x2b, 0xb2, 0x86, 0x9f, 0xc2, 0x5d, 0x2f, 0xf0, 0x52, 0x16, 0x5e, 0x11, 0xf1, 0x6e,
	0xd7, 0x4f, 0x62, 0x46, 0x93, 0xc8, 0x00, 0xe1, 0xfe, 0xb0, 0x50, 0x72, 0x22, 0x13, 0xa9, 0x12,
	0xa9, 0x8c, 0x12, 0xff, 0x32, 0x8c, 0x5f, 0xbb, 0x94, 0xf8, 0x57, 0xc6, 0x40, 0x60, 0x87, 0x85,
	0x10, 0x13, 0xff, 0x8a, 0x6f, 0xc8, 0x5c, 0x27, 0x88, 0x24, 0x39, 0x33, 0x86, 0x72, 0x43, 0xe6,
	0x32, 0x47, 0x8a, 0x38, 0xd5, 0x92, 0x26, 0x0f, 0x4e, 0x51, 0x1d, 0xc9, 0x34, 0x32, 0xc9, 0x13,
	0xa7, 0xbe, 0xa2, 0xfa, 0x14, 0x8c, 0x34, 0x89, 0x22, 0xb7, 0xce, 0x66, 0x4f, 0xd8, 0xdc, 0xe1,
	0x7a, 0xa7, 0xc6, 0x8e, 0x67, 0xbe, 0xd6, 0x6e, 0x5f, 0xda, 0x71, 0xfd, 0x2d, 0x3b, 0xb1, 0x2f,
	0xf2, 0xfe, 0xe3, 0x06, 0x99, 0xa1, 0x8b, 0x00, 0x40, 0x8a, 0x70, 0xea, 0x67, 0xe8, 0xa7, 0x70,
	0xa7, 0x02, 0x58, 0x97, 0xf7, 0x40, 0x94, 0x17, 0xad, 0x91, 0x65, 0x91, 0x1f, 0xc2, 0xfe, 0xda,
	0x42, 0xd6, 0x1a, 0xc9, 0xfe, 0x2a, 0xc1, 0xa2, 0xe2, 0x8f, 0xe1, 0x5e, 0xc9, 0x56, 0x19, 0x28,
	0xc2, 0x87, 0x02, 0x7e, 0xa8, 0x92, 0x53, 0x5d, 0x57, 0xcd, 0xdf, 0x69, 0x80, 0xce, 0xf3, 0x88,
	0x85, 0x69, 0x44, 0xae, 0x49, 0x50, 0xfc, 0x8c, 0x9a, 0x03, 0xf2, 0xcb, 0xdf, 0x80, 0x2e, 0x95,
	0x52, 0x75, 0xed, 0xde, 0xfb, 0x8e, 0x5f, 0xba, 0xf8, 0xc0, 0xbf, 0xf5, 0x5b, 0xf9, 0x63, 0xbe,
	0x15, 0x4b, 0x27, 0x72, 0x43, 0xd8, 0xda, 0x3d, 0x0b, 0xd3, 0x02, 0x65, 0xfe, 0x46, 0x83, 0xc3,
	0x0d, 0x5e, 0xea, 0x07, 0xca, 0x29, 0xf4, 0xa8, 0x7a, 0x56, 0x74, 0xee, 0x6d, 0x7b, 0x92, 0x5a,
	0x5c, 0xe2, 0xd0, 0x97, 0x30, 0xda, 0xcc, 0x87, 0xa4, 0x50, 0xbb, 0x98, 0xcb, 0xb4, 0xe0, 0x61,
	0x56, 0x39, 0xbd, 0xea, 0x88, 0x7f, 0x0a, 0x3c, 0xfe, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc7,
	0xc7, 0xce, 0xa6, 0x22, 0x10, 0x00, 0x00,
}
