// Code generated by protoc-gen-go. DO NOT EDIT.
// source: request.proto

package sturdyengine

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Calls                []*ProcedureCall `protobuf:"bytes,1,rep,name=calls,proto3" json:"calls,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_request_323ac712d6585f8a, []int{0}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetCalls() []*ProcedureCall {
	if m != nil {
		return m.Calls
	}
	return nil
}

type ProcedureCall struct {
	Service              string      `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Procedure            string      `protobuf:"bytes,2,opt,name=procedure,proto3" json:"procedure,omitempty"`
	ServiceId            uint32      `protobuf:"varint,4,opt,name=serviceId,proto3" json:"serviceId,omitempty"`
	ProcedureId          uint32      `protobuf:"varint,5,opt,name=procedureId,proto3" json:"procedureId,omitempty"`
	Arguments            []*Argument `protobuf:"bytes,3,rep,name=arguments,proto3" json:"arguments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ProcedureCall) Reset()         { *m = ProcedureCall{} }
func (m *ProcedureCall) String() string { return proto.CompactTextString(m) }
func (*ProcedureCall) ProtoMessage()    {}
func (*ProcedureCall) Descriptor() ([]byte, []int) {
	return fileDescriptor_request_323ac712d6585f8a, []int{1}
}
func (m *ProcedureCall) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcedureCall.Unmarshal(m, b)
}
func (m *ProcedureCall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcedureCall.Marshal(b, m, deterministic)
}
func (dst *ProcedureCall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcedureCall.Merge(dst, src)
}
func (m *ProcedureCall) XXX_Size() int {
	return xxx_messageInfo_ProcedureCall.Size(m)
}
func (m *ProcedureCall) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcedureCall.DiscardUnknown(m)
}

var xxx_messageInfo_ProcedureCall proto.InternalMessageInfo

func (m *ProcedureCall) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *ProcedureCall) GetProcedure() string {
	if m != nil {
		return m.Procedure
	}
	return ""
}

func (m *ProcedureCall) GetServiceId() uint32 {
	if m != nil {
		return m.ServiceId
	}
	return 0
}

func (m *ProcedureCall) GetProcedureId() uint32 {
	if m != nil {
		return m.ProcedureId
	}
	return 0
}

func (m *ProcedureCall) GetArguments() []*Argument {
	if m != nil {
		return m.Arguments
	}
	return nil
}

type Argument struct {
	Position             uint32   `protobuf:"varint,1,opt,name=position,proto3" json:"position,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Argument) Reset()         { *m = Argument{} }
func (m *Argument) String() string { return proto.CompactTextString(m) }
func (*Argument) ProtoMessage()    {}
func (*Argument) Descriptor() ([]byte, []int) {
	return fileDescriptor_request_323ac712d6585f8a, []int{2}
}
func (m *Argument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Argument.Unmarshal(m, b)
}
func (m *Argument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Argument.Marshal(b, m, deterministic)
}
func (dst *Argument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Argument.Merge(dst, src)
}
func (m *Argument) XXX_Size() int {
	return xxx_messageInfo_Argument.Size(m)
}
func (m *Argument) XXX_DiscardUnknown() {
	xxx_messageInfo_Argument.DiscardUnknown(m)
}

var xxx_messageInfo_Argument proto.InternalMessageInfo

func (m *Argument) GetPosition() uint32 {
	if m != nil {
		return m.Position
	}
	return 0
}

func (m *Argument) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "sturdyengine.Request")
	proto.RegisterType((*ProcedureCall)(nil), "sturdyengine.ProcedureCall")
	proto.RegisterType((*Argument)(nil), "sturdyengine.Argument")
}

func init() { proto.RegisterFile("request.proto", fileDescriptor_request_323ac712d6585f8a) }

var fileDescriptor_request_323ac712d6585f8a = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xbd, 0x4e, 0xc3, 0x30,
	0x14, 0x85, 0x65, 0x4a, 0x68, 0x73, 0xdb, 0x2c, 0x57, 0x08, 0x59, 0xc0, 0x10, 0x65, 0xca, 0x14,
	0x89, 0x9f, 0xb1, 0x0b, 0x62, 0xea, 0x86, 0xfc, 0x06, 0x21, 0xbe, 0xaa, 0x2c, 0x19, 0x3b, 0xf8,
	0xa7, 0x12, 0x0f, 0xc7, 0xbb, 0x21, 0xec, 0xa6, 0x69, 0xc7, 0x73, 0xbe, 0x6f, 0xb8, 0xe7, 0x42,
	0xe5, 0xe8, 0x3b, 0x92, 0x0f, 0xdd, 0xe8, 0x6c, 0xb0, 0xb8, 0xf1, 0x21, 0x3a, 0xf9, 0x43, 0x66,
	0xaf, 0x0c, 0x35, 0x5b, 0x58, 0x8a, 0x8c, 0xf1, 0x09, 0x8a, 0xa1, 0xd7, 0xda, 0x73, 0x56, 0x2f,
	0xda, 0xf5, 0xf3, 0x43, 0x77, 0x2e, 0x76, 0x1f, 0xce, 0x0e, 0x24, 0xa3, 0xa3, 0xf7, 0x5e, 0x6b,
	0x91, 0xcd, 0xe6, 0x97, 0x41, 0x75, 0x01, 0x90, 0xc3, 0xd2, 0x93, 0x3b, 0xa8, 0x81, 0x38, 0xab,
	0x59, 0x5b, 0x8a, 0x29, 0xe2, 0x23, 0x94, 0xe3, 0xa4, 0xf2, 0xab, 0xc4, 0xe6, 0xe2, 0x9f, 0x1e,
	0xc5, 0x9d, 0xe4, 0xd7, 0x35, 0x6b, 0x2b, 0x31, 0x17, 0x58, 0xc3, 0xfa, 0xa4, 0xee, 0x24, 0x2f,
	0x12, 0x3f, 0xaf, 0xf0, 0x15, 0xca, 0xde, 0xed, 0xe3, 0x17, 0x99, 0xe0, 0xf9, 0x22, 0x0d, 0xb8,
	0xbb, 0x1c, 0xf0, 0x76, 0xc4, 0x62, 0x16, 0x9b, 0x2d, 0xac, 0xa6, 0x1a, 0xef, 0x61, 0x35, 0x5a,
	0xaf, 0x82, 0xb2, 0x26, 0x9d, 0x5e, 0x89, 0x53, 0xc6, 0x5b, 0x28, 0x0e, 0xbd, 0x8e, 0xf9, 0xee,
	0x8d, 0xc8, 0xe1, 0xf3, 0x26, 0x3d, 0xf4, 0xe5, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xa1, 0xd8, 0x64,
	0xa2, 0x61, 0x01, 0x00, 0x00,
}
