// Code generated by protoc-gen-go. DO NOT EDIT.
// source: response.proto

package sturdyengine

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Response struct {
	Error                *Error             `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Results              []*ProcedureResult `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_response_922f178208a1b55a, []int{0}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Response) GetResults() []*ProcedureResult {
	if m != nil {
		return m.Results
	}
	return nil
}

type ProcedureResult struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProcedureResult) Reset()         { *m = ProcedureResult{} }
func (m *ProcedureResult) String() string { return proto.CompactTextString(m) }
func (*ProcedureResult) ProtoMessage()    {}
func (*ProcedureResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_response_922f178208a1b55a, []int{1}
}
func (m *ProcedureResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcedureResult.Unmarshal(m, b)
}
func (m *ProcedureResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcedureResult.Marshal(b, m, deterministic)
}
func (dst *ProcedureResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcedureResult.Merge(dst, src)
}
func (m *ProcedureResult) XXX_Size() int {
	return xxx_messageInfo_ProcedureResult.Size(m)
}
func (m *ProcedureResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcedureResult.DiscardUnknown(m)
}

var xxx_messageInfo_ProcedureResult proto.InternalMessageInfo

func (m *ProcedureResult) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *ProcedureResult) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type Error struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	StackTrace           string   `protobuf:"bytes,4,opt,name=stack_trace,json=stackTrace,proto3" json:"stack_trace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_response_922f178208a1b55a, []int{2}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (dst *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(dst, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *Error) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Error) GetStackTrace() string {
	if m != nil {
		return m.StackTrace
	}
	return ""
}

func init() {
	proto.RegisterType((*Response)(nil), "sturdyengine.Response")
	proto.RegisterType((*ProcedureResult)(nil), "sturdyengine.ProcedureResult")
	proto.RegisterType((*Error)(nil), "sturdyengine.Error")
}

func init() { proto.RegisterFile("response.proto", fileDescriptor_response_922f178208a1b55a) }

var fileDescriptor_response_922f178208a1b55a = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0xb1, 0x4e, 0xc3, 0x40,
	0x0c, 0x86, 0x95, 0xb6, 0xa1, 0xd4, 0xa9, 0x40, 0x32, 0x0c, 0xb7, 0x20, 0xa2, 0x4c, 0x61, 0xc9,
	0x50, 0x06, 0x9e, 0x80, 0x1d, 0x59, 0xec, 0x28, 0x5c, 0x2c, 0x14, 0x51, 0xee, 0x22, 0xfb, 0x52,
	0xc1, 0xdb, 0xa3, 0x3a, 0x54, 0x0a, 0x6c, 0x6c, 0xf7, 0xff, 0xdf, 0x77, 0xb6, 0x64, 0xb8, 0x10,
	0xd6, 0x21, 0x06, 0xe5, 0x66, 0x90, 0x98, 0x22, 0x6e, 0x35, 0x8d, 0xd2, 0x7d, 0x71, 0x78, 0xeb,
	0x03, 0x57, 0x01, 0xce, 0xe9, 0x87, 0xe3, 0x1d, 0xe4, 0x2c, 0x12, 0xc5, 0x65, 0x65, 0x56, 0x17,
	0xbb, 0xab, 0x66, 0x6e, 0x36, 0x8f, 0x47, 0x44, 0x93, 0x81, 0x0f, 0xb0, 0x16, 0xd6, 0x71, 0x9f,
	0xd4, 0x2d, 0xca, 0x65, 0x5d, 0xec, 0x6e, 0x7e, 0xcb, 0x4f, 0x12, 0x3d, 0x77, 0xa3, 0x30, 0x99,
	0x45, 0x27, 0xbb, 0x22, 0xb8, 0xfc, 0xc3, 0xfe, 0xb3, 0xf6, 0x1a, 0xf2, 0x43, 0xbb, 0x1f, 0xd9,
	0x2d, 0xca, 0xac, 0xde, 0xd2, 0x14, 0xaa, 0x4f, 0xc8, 0xcd, 0x42, 0x07, 0x6b, 0x65, 0x39, 0xf4,
	0x9e, 0x6d, 0xd6, 0x86, 0x4e, 0x11, 0x11, 0x56, 0xa1, 0xfd, 0x98, 0xfe, 0x6d, 0xc8, 0xde, 0x58,
	0x42, 0xd1, 0xb1, 0x7a, 0xe9, 0x87, 0xd4, 0xc7, 0xe0, 0x96, 0x86, 0xe6, 0x15, 0xde, 0x42, 0xa1,
	0xa9, 0xf5, 0xef, 0x2f, 0x49, 0x5a, 0xcf, 0x6e, 0x65, 0x06, 0x58, 0xf5, 0x7c, 0x6c, 0x5e, 0xcf,
	0xec, 0xa4, 0xf7, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xad, 0xf4, 0x69, 0x28, 0x64, 0x01, 0x00,
	0x00,
}
